language: ruby
rvm:
  - 2.2.5
branches:
  except:
  - gh-pages
install: gem install jekyll html-proofer github-pages
script: bundle exec jekyll build && htmlproofer ./_site
before_install:
- openssl aes-256-cbc -K $encrypted_f53b1ef3be1c_key -iv $encrypted_f53b1ef3be1c_iv
  -in id_rsa.enc -out id_rsa -d
after_sucess:
  - npm run gh-pages-travis
env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="Karissa Demi"
    - GIT_EMAIL="k@karissademi.com"
    - DEPLOY_BRANCH="master"
    - SOURCE_DIR="./"
